import { Component, OnInit, ViewEncapsulation, OnDestroy, Input } from '@angular/core';
import { SessionDataService } from 'src/app/conf/session-data.service';
import { GameInfoI, GameState } from '../../models/game-info';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { ConfigService } from 'src/app/conf/config.service';

@Component({
  selector: 'choose-word',
  templateUrl: './choose-word.component.html',
  styleUrls: ['./choose-word.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class ChooseWordComponent implements OnInit {
  submitted = false;
  processing = false;
  message: string;
  choosingWordForm: FormGroup;

  @Input('playerNumber') private _playerNumber: number;

  @Input() startTimer = (): void => {
    this._sessionDataService.timer = 60;
    setTimeout(async () => {
      await this.decTimer();
    }, 1000);
  };

  private async decTimer() {
    if (this._sessionDataService.timer > 0 && this._sessionDataService.stateManagement.gameInfo.state === GameState.ChoosingWord) {
      this._sessionDataService.timer--;
      if (this.isChoosing() && this._sessionDataService.timer === 0) {
        this.submitted = true;
        this.processing = true;
        if (this.invalidWord()) {
          this.choosingWordForm.get('word').setValue('autogeneratedValue');
          this.choosingWordForm.get('word').updateValueAndValidity();
        }
        await this.chooseWord();
      } else {
        setTimeout(async () => {
          await this.decTimer();
        }, 1000);
      }
    }
  }

  public get word(): string {
    return this._sessionDataService.stateManagement.gameInfo.word;
  }

  constructor(private _formBuilder: FormBuilder, private _sessionDataService: SessionDataService, private _configService: ConfigService) {
  }

  ngOnInit() {
    this.choosingWordForm = this._formBuilder.group({
      word: ['', [Validators.required, Validators.pattern('^[a-zA-Z0-9]+$')]]
    });
    if (this._sessionDataService.stateManagement.gameInfo.state === GameState.ChoosingWord) {
      this.startTimer();
    }
  }

  public showWord(): boolean {
    return this._sessionDataService.stateManagement.gameInfo.state !== GameState.ChoosingWord;
  }

  public isChoosing(): boolean {
    return this._sessionDataService.stateManagement.gameInfo.state === GameState.ChoosingWord && this._playerNumber === this._sessionDataService.stateManagement.gameInfo.playerChoosing;
  }

  public invalidWord(): boolean {
    return (this.submitted && this.choosingWordForm.controls.word.errors != null);
  }

  public async chooseWord() {
    this.submitted = true;
    this.processing = true;

    if (this.choosingWordForm.invalid == true) {
      this.processing = false;
      return;
    }
    else {
      try {
        let gameInfo: GameInfoI = await this._configService.chooseWord(this._sessionDataService.stateManagement.gameInfo._id, this.choosingWordForm.get('word').value, this._sessionDataService.stateManagement.socket);
        if (!gameInfo) {
          throw 0;
        }
        this._sessionDataService.timer = undefined;
        this._sessionDataService.stateManagement.changeGameInfo(gameInfo);
        this.choosingWordForm.reset();
      } catch (error) {
        this.message = 'Something went wrong';
        setTimeout(() => this.message = undefined, 1000);
      } finally {
        this.submitted = false;
        this.processing = false;
      }
    }
  }
}
